### ISSUE TITLE
Bug: optional variable does not exist on query

### ISSUE THREAD

**Issue by svrcekmichal** [Youshido/GraphQL#59]
Query:
```
query userById($offset:Int) {
  user(id: 2) {
    id
    photoAlbums(offset: $offset) {
      edges {
        id
      }
    }
  }
}
```
Response: 
```
{
  "data": {
    "user": {
      "id": 2,
      "photoAlbums": null
    }
  },
  "errors": [
    {
      "message": "Variable \"offset\" does not exist for query \"photoAlbums\""
    }
  ]
}
```

If i dont use named query
```
{
  user(id: 2) {
    id
    photoAlbums {
      edges {
        id
      }
    }
  }
}
```
response is 
```
{
  "data": {
    "user": {
      "id": 2,
      "photoAlbums": {
        "edges": [
          {
            "id": 10000965
          },
          ....
        ]
      }
    }
  }
}
```

**Comment by svrcekmichal** [comment]
First hint is that if `offset` is `0` in
```
/** @var Variable $requestVariable */
$requestVariable = $request->getVariable($variable->getName());
if (!$requestVariable) {
    $this->executionContext->addError(new ResolveException(sprintf('Variable "%s" does not exist for query "%s"', $argument->getName(), $field->getName())));
    return false;
}
$variable->setValue($requestVariable);
```

**Comment by viniychuk** [comment]
@svrcekmichal 
It's already fixed in the latest commits... you sure you're using the latest version?

**Comment by svrcekmichal** [comment]
@viniychuk going to check that

**Comment by svrcekmichal** [comment]
Updated, I'm using `dev-master` so have latest, the issue with zero is fixed. But even in older version there have been one and that's argument does not need to be required, this check will throw even for variables that are optional

**Comment by rovansteen** [comment]
Am I right that this is still an issue? It still throws an error if there is an optional variable not present on the query.

**Comment by viniychuk** [comment]
@rovansteen 
No it's not, at least it's not supposed to be :)
Are you sure you're using the latest version?

**Comment by rovansteen** [comment]
@viniychuk I'm using the latest version of https://github.com/Youshido/GraphQLBundle.

But if I understand the code correctly here: https://github.com/Youshido/GraphQL/blob/5c21ca7ce6e2ee149aeaa622b24e9b2463320523/src/Validator/ResolveValidator/ResolveValidator.php#L175 then it will always throw an error if there is a variable missing.

**Comment by svrcekmichal** [comment]
@viniychuk It's still issue, I told you up there, there've been two bugs. One with zero, taht was fixed, second with optional variable that must be present in query, that wasn't fixed. I was busy lately so couldn't reply to close of issue

**Comment by svrcekmichal** [comment]
@viniychuk you should probably reopen this issue
